url: https://trunkbasedreview.kanekotic.com/
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Trunk Based Review
description: Asynchronous peer reviewing for trunk-based development
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]